apiVersion: apps/v1
kind: Deployment
metadata:
    name: myapp-deployment
spec:
    replicas: 2
    selector:
       matchLabels:
          app: myapp
    template:
       metadata:
          labels:
             app: myapp
       spec:
          containers:
          - name: myapp
            image: alia1221/architect_hw_1:v1
            imagePullPolicy: "Always"
            ports:
              - name: web
                containerPort: 80
            livenessProbe:
              httpGet:
                port: 80
                path: /
              initialDelaySeconds: 10
              periodSeconds: 5
              timeoutSeconds: 2
            readinessProbe:
              httpGet:
                port: 80
                path: /health/
              initialDelaySeconds: 10
              periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: myapp-service
spec:
  selector:
    app: myapp
  ports:
    - protocol: TCP
      port: 8001
      targetPort: web
  type: NodePort

---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: hw-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2$3
spec:
  rules:
  - host: arch.homework
    http:
      paths:
        - path: /otusapp/([A-z_]{1,128}?)/(.*)($|/)
          backend:
            serviceName: myapp-service
            servicePort: 8001